[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(sbtMapExec 5 __eb967477-d683-4292-9f5c-bb1335e8457b, None, None)
[debug] > Exec(bspBuildTargetDependencySources file:/home/vitalis/type_directedPR/#td/Compile file:/home/vitalis/type_directedPR/#td/Test, Some(__eb967477-d683-4292-9f5c-bb1335e8457b), Some(CommandSource(network-3)))
[debug] jsonRpcNotify: JsonRpcNotificationMessage(2.0, build/logMessage, {"type":4,"message":"Processing"})
[debug] Evaluating tasks: bspBuildTargetDependencySources
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[debug] Unhandled notification received: build/exit: JsonRpcNotificationMessage(2.0, build/exit, null)
[warn] Canceling execution...
[debug] Forcing garbage collection...
[debug] jsonRpcNotify: JsonRpcNotificationMessage(2.0, shutdown, [false,null])
[debug] jsonRpcNotify: JsonRpcNotificationMessage(2.0, shutdown, [true,null])
[error] java.util.concurrent.RejectedExecutionException
[error] 	at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:242)
[error] 	at sbt.Execute.submit(Execute.scala:282)
[error] 	at sbt.Execute.ready(Execute.scala:262)
[error] 	at sbt.Execute.notifyDone(Execute.scala:201)
[error] 	at sbt.Execute.$anonfun$retire$2(Execute.scala:172)
[error] 	at sbt.Execute.$anonfun$retire$2$adapted(Execute.scala:171)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at sbt.Execute.retire(Execute.scala:171)
[error] 	at sbt.Execute.$anonfun$work$2(Execute.scala:299)
[error] 	at sbt.Execute$$anon$1.process(Execute.scala:27)
[error] 	at sbt.Execute.next$1(Execute.scala:117)
[error] 	at sbt.Execute.processAll(Execute.scala:127)
[error] 	at sbt.Execute.runKeep(Execute.scala:95)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:472)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:471)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:494)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:181)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
[error] 	at sbt.Command$.process(Command.scala:189)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:245)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:269)
[error] 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:286)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:322)
[error] 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:162)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:143)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:188)
[error] 	at sbt.xMain$.$anonfun$run$6(Main.scala:100)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withIn(Console.scala:230)
[error] 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:542)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withStreams$2(Terminal.scala:337)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:532)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withErr(Console.scala:196)
[error] 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:532)
[error] 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:337)
[error] 	at sbt.xMain$.run(Main.scala:83)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
[error] 	at sbt.xMain.run(Main.scala:46)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:120)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.util.concurrent.RejectedExecutionException
[error] Use 'last' for the full log.
[debug] > Exec(resumeFromFailure, None, None)
[debug] > Exec(sbtPopOnFailure, None, None)
[debug] > Exec(sbtReportResult 5, Some(5), Some(CommandSource(network-3)))
[debug] > Exec(shell, None, None)
